/* ═══════════════════════════════════════════════════════
   MINI-GAME SHARED HELPERS
   ═══════════════════════════════════════════════════════ */

const { esc, fetchAll, safeRead } = require('./common');

/* ── Elo, for head-to-head song ranking ──────────────────
   K is deliberately modest so one lucky run can't rocket a mid-tier song to
   the top, and songs with few appearances get a higher K so they converge
   faster — that plus the pair-selection bias below is what stops
   first-appearance bias from deciding the whole board.                    */
const BASE_ELO = 1500;

function kFactor(appearances) {
    if (appearances < 10) return 48;
    if (appearances < 40) return 32;
    return 20;
}

function expectedScore(ratingA, ratingB) {
    return 1 / (1 + Math.pow(10, (ratingB - ratingA) / 400));
}

/** Returns the two new ratings after A beats B. */
function applyElo(ratingA, ratingB, appearancesA, appearancesB) {
    const expA = expectedScore(ratingA, ratingB);
    const expB = 1 - expA;
    return {
        a: Math.round(ratingA + kFactor(appearancesA) * (1 - expA)),
        b: Math.round(ratingB + kFactor(appearancesB) * (0 - expB)),
    };
}

/**
 * Pick a pair, biased toward under-exposed songs.
 *
 * "Reshuffle periodically so a mid-tier song doesn't ride a lucky streak to
 * the top on first-appearance bias." Two mechanisms do that here:
 *   1. The candidate pool is weighted by 1/(appearances+1), so songs nobody
 *      has judged surface far more often than well-established ones.
 *   2. The opponent is drawn from a rating-neighbourhood, so matches are
 *      informative rather than blowouts — a 1900 vs 1200 pairing teaches the
 *      board almost nothing.
 */
function pickPair(songs, excludeIds = []) {
    const pool = songs.filter((s) => !excludeIds.includes(s.id));
    if (pool.length < 2) return null;

    // 1. Weighted draw for the first song.
    const weights = pool.map((s) => 1 / ((s.appearances || 0) + 1));
    const total = weights.reduce((a, b) => a + b, 0);
    let roll = Math.random() * total;
    let firstIdx = 0;
    for (let i = 0; i < pool.length; i++) {
        roll -= weights[i];
        if (roll <= 0) { firstIdx = i; break; }
    }
    const first = pool[firstIdx];

    // 2. Opponent from the rating neighbourhood.
    const rest = pool.filter((s) => s.id !== first.id);
    rest.sort((a, b) => Math.abs((a.rating || BASE_ELO) - (first.rating || BASE_ELO))
                      - Math.abs((b.rating || BASE_ELO) - (first.rating || BASE_ELO)));
    const neighbourhood = rest.slice(0, Math.max(3, Math.ceil(rest.length * 0.35)));
    const second = neighbourhood[Math.floor(Math.random() * neighbourhood.length)];

    return Math.random() < 0.5 ? [first, second] : [second, first];
}

/* ── Trivia sourcing ─────────────────────────────────────
   HARD RULE from the brief: "questions must be generated from
   archive-approved material only. Getting a fact wrong about her, in her own
   app, in a demo, is a disaster."

   So the only sources permitted are:
     - Archive rows with Status 'Approved' (her own recorded words), and
     - MusicContent rows, which are her discography as entered by the team.

   Nothing is inferred, nothing is generated by a model, and any question
   whose answer cannot be read directly off a record is not asked.          */
async function loadApprovedFacts(base, { limit = 200 } = {}) {
    const facts = [];

    const music = await safeRead(
        () => fetchAll(base, 'MusicContent', {
            filterByFormula: `{Status} != 'Archived'`,
        }, limit),
        []
    );

    for (const r of music) {
        const f = r.fields;
        const title = f.Title;
        if (!title) continue;
        if (f.Year) {
            facts.push({
                kind: 'year',
                subject: title,
                answer: String(f.Year),
                sourceId: r.id,
                sourceKind: 'MusicContent',
            });
        }
        if (f.Era) {
            facts.push({
                kind: 'era',
                subject: title,
                answer: String(f.Era),
                sourceId: r.id,
                sourceKind: 'MusicContent',
            });
        }
    }

    const archive = await safeRead(
        () => fetchAll(base, 'Archive', {
            filterByFormula: `AND({Status} = 'Approved', {TranscriptStatus} = 'Done')`,
        }, 60),
        []
    );

    for (const r of archive) {
        const f = r.fields;
        if (!f.Title || !f.TranscriptPlain) continue;
        facts.push({
            kind: 'quote',
            subject: f.Title,
            answer: String(f.TranscriptPlain).slice(0, 400),
            sourceId: r.id,
            sourceKind: 'Archive',
            verified: true,
        });
    }

    return facts;
}

/** Build multiple-choice distractors from the same fact family — never invented. */
function buildChoices(correct, siblings, count = 4) {
    const pool = [...new Set(siblings.filter((s) => s && s !== correct))];
    // Shuffle
    for (let i = pool.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [pool[i], pool[j]] = [pool[j], pool[i]];
    }
    const choices = [correct, ...pool.slice(0, count - 1)];
    for (let i = choices.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [choices[i], choices[j]] = [choices[j], choices[i]];
    }
    return choices;
}

/* ── Millionaire ladder ──────────────────────────────────
   The bank-or-risk decision at each tier is the entire game — it's the reason
   to open the app, not the trivia. Safe levels give the decision teeth.     */
const LADDER = [
    { level: 1,  points: 5,    safe: false },
    { level: 2,  points: 10,   safe: false },
    { level: 3,  points: 20,   safe: false },
    { level: 4,  points: 40,   safe: false },
    { level: 5,  points: 80,   safe: true  },
    { level: 6,  points: 140,  safe: false },
    { level: 7,  points: 220,  safe: false },
    { level: 8,  points: 340,  safe: false },
    { level: 9,  points: 500,  safe: false },
    { level: 10, points: 750,  safe: true  },
    { level: 11, points: 1100, safe: false },
    { level: 12, points: 1600, safe: false },
    { level: 13, points: 2300, safe: false },
    { level: 14, points: 3200, safe: false },
    { level: 15, points: 5000, safe: true  },
];

function safeFloor(level) {
    let floor = 0;
    for (const rung of LADDER) {
        if (rung.level < level && rung.safe) floor = rung.points;
    }
    return floor;
}

module.exports = {
    BASE_ELO, kFactor, expectedScore, applyElo, pickPair,
    loadApprovedFacts, buildChoices, LADDER, safeFloor,
};
